### ISSUE TITLE
Port over changes we make here to old mini repo

### ISSUE THREAD

**Issue by patudom** [cosmicds/radwave-in-motion#2]
This is a reminder to ourselves that we either need to disable the old minids/radwave link that the SME team already has access to and/or forward it to the new link, or port over whatever changes we make here to the mini repo so both links show the same thing.

**Comment by patudom** [comment]
@Carifio24, John and I discussed this briefly and thought you might have ideas for the best way to handle this issue.

**Comment by Carifio24** [comment]
With https://github.com/cosmicds/minids/pull/349, https://github.com/cosmicds/minids/pull/350, https://github.com/cosmicds/minids/pull/351, this should be resolved, as navigating to the old radwave mini will now redirect to the deployed story from here.
